import { Position } from "../types";

/**
 * Real-world Premier League club & roster data (2025-26 season, approximate).
 *
 * Names, nationalities and club identities are factual information, not creative
 * works — that's why this is safe to include. What's deliberately NOT here: club
 * crests/logos or kit graphics, which ARE protected trademarks. Colors below are
 * just the well-known shirt colors (facts), not exact trademarked shades/designs.
 *
 * Rosters are a good-faith approximation as of this project's knowledge cutoff.
 * The transfer window never stops, so some entries will drift from reality —
 * treat this as a realistic starting point, not a live feed. Edit freely.
 *
 * `tier` (1-5) is a rough current-quality signal the game engine uses to scale
 * generated attributes — it is not an official rating of any kind.
 */

export interface SeedPlayer {
  name: string;
  position: Position;
  age: number;
  nationality: string;
  tier: number; // 1 (squad depth) - 5 (world class)
}

export interface SeedClub {
  name: string;
  shortName: string;
  primaryColor: string;
  secondaryColor: string;
  players: SeedPlayer[];
}

export const PREMIER_LEAGUE_CLUBS: SeedClub[] = [
  {
    name: "Arsenal",
    shortName: "Arsenal",
    primaryColor: "#EF0107",
    secondaryColor: "#063672",
    players: [
      { name: "David Raya", position: "GK", age: 30, nationality: "Spain", tier: 4 },
      { name: "William Saliba", position: "CB", age: 24, nationality: "France", tier: 5 },
      { name: "Gabriel Magalhães", position: "CB", age: 27, nationality: "Brazil", tier: 5 },
      { name: "Jurriën Timber", position: "RB", age: 24, nationality: "Netherlands", tier: 4 },
      { name: "Riccardo Calafiori", position: "LB", age: 23, nationality: "Italy", tier: 4 },
      { name: "Ben White", position: "RB", age: 27, nationality: "England", tier: 4 },
      { name: "Declan Rice", position: "CM", age: 26, nationality: "England", tier: 5 },
      { name: "Martin Ødegaard", position: "AM", age: 26, nationality: "Norway", tier: 5 },
      { name: "Mikel Merino", position: "CM", age: 29, nationality: "Spain", tier: 4 },
      { name: "Jorginho", position: "DM", age: 33, nationality: "Italy", tier: 3 },
      { name: "Bukayo Saka", position: "RW", age: 24, nationality: "England", tier: 5 },
      { name: "Gabriel Martinelli", position: "LW", age: 24, nationality: "Brazil", tier: 4 },
      { name: "Leandro Trossard", position: "LW", age: 30, nationality: "Belgium", tier: 4 },
      { name: "Viktor Gyökeres", position: "ST", age: 27, nationality: "Sweden", tier: 5 },
      { name: "Kai Havertz", position: "ST", age: 26, nationality: "Germany", tier: 4 },
      { name: "Myles Lewis-Skelly", position: "LB", age: 19, nationality: "England", tier: 3 },
    ],
  },
  {
    name: "Aston Villa",
    shortName: "Aston Villa",
    primaryColor: "#7A263A",
    secondaryColor: "#94BEE5",
    players: [
      { name: "Emiliano Martínez", position: "GK", age: 33, nationality: "Argentina", tier: 5 },
      { name: "Ezri Konsa", position: "CB", age: 28, nationality: "England", tier: 4 },
      { name: "Pau Torres", position: "CB", age: 28, nationality: "Spain", tier: 4 },
      { name: "Matty Cash", position: "RB", age: 28, nationality: "Poland", tier: 3 },
      { name: "Lucas Digne", position: "LB", age: 32, nationality: "France", tier: 3 },
      { name: "Boubacar Kamara", position: "DM", age: 25, nationality: "France", tier: 4 },
      { name: "Youri Tielemans", position: "CM", age: 28, nationality: "Belgium", tier: 4 },
      { name: "John McGinn", position: "CM", age: 31, nationality: "Scotland", tier: 4 },
      { name: "Amadou Onana", position: "CM", age: 24, nationality: "Belgium", tier: 4 },
      { name: "Morgan Rogers", position: "AM", age: 23, nationality: "England", tier: 4 },
      { name: "Emiliano Buendía", position: "AM", age: 29, nationality: "Argentina", tier: 3 },
      { name: "Ollie Watkins", position: "ST", age: 30, nationality: "England", tier: 5 },
      { name: "Jadon Sancho", position: "LW", age: 26, nationality: "England", tier: 3 },
    ],
  },
  {
    name: "Bournemouth",
    shortName: "Bournemouth",
    primaryColor: "#DA291C",
    secondaryColor: "#000000",
    players: [
      { name: "Đorđe Petrović", position: "GK", age: 26, nationality: "Serbia", tier: 3 },
      { name: "Marcos Senesi", position: "CB", age: 28, nationality: "Argentina", tier: 3 },
      { name: "Illia Zabarnyi", position: "CB", age: 23, nationality: "Ukraine", tier: 4 },
      { name: "Adam Smith", position: "RB", age: 34, nationality: "England", tier: 2 },
      { name: "Álex Jiménez", position: "LB", age: 20, nationality: "Spain", tier: 3 },
      { name: "Ryan Christie", position: "CM", age: 30, nationality: "Scotland", tier: 3 },
      { name: "Alex Scott", position: "CM", age: 22, nationality: "England", tier: 3 },
      { name: "David Brooks", position: "AM", age: 28, nationality: "Wales", tier: 3 },
      { name: "Antoine Semenyo", position: "RW", age: 25, nationality: "Ghana", tier: 4 },
      { name: "Justin Kluivert", position: "RW", age: 26, nationality: "Netherlands", tier: 3 },
      { name: "Evanilson", position: "ST", age: 26, nationality: "Brazil", tier: 4 },
    ],
  },
  {
    name: "Brentford",
    shortName: "Brentford",
    primaryColor: "#E30613",
    secondaryColor: "#FBB800",
    players: [
      { name: "Caoimhín Kelleher", position: "GK", age: 27, nationality: "Ireland", tier: 3 },
      { name: "Nathan Collins", position: "CB", age: 24, nationality: "Ireland", tier: 4 },
      { name: "Sepp van den Berg", position: "CB", age: 23, nationality: "Netherlands", tier: 3 },
      { name: "Rico Henry", position: "LB", age: 28, nationality: "England", tier: 3 },
      { name: "Keane Lewis-Potter", position: "LB", age: 24, nationality: "England", tier: 3 },
      { name: "Vitaly Janelt", position: "CM", age: 27, nationality: "Germany", tier: 3 },
      { name: "Yehor Yarmoliuk", position: "CM", age: 21, nationality: "Ukraine", tier: 3 },
      { name: "Mikkel Damsgaard", position: "AM", age: 25, nationality: "Denmark", tier: 4 },
      { name: "Kevin Schade", position: "LW", age: 23, nationality: "Germany", tier: 4 },
      { name: "Igor Thiago", position: "ST", age: 23, nationality: "Brazil", tier: 4 },
    ],
  },
  {
    name: "Brighton & Hove Albion",
    shortName: "Brighton",
    primaryColor: "#0057B8",
    secondaryColor: "#FFFFFF",
    players: [
      { name: "Bart Verbruggen", position: "GK", age: 23, nationality: "Netherlands", tier: 3 },
      { name: "Lewis Dunk", position: "CB", age: 34, nationality: "England", tier: 3 },
      { name: "Jan Paul van Hecke", position: "CB", age: 25, nationality: "Netherlands", tier: 4 },
      { name: "Tariq Lamptey", position: "RB", age: 25, nationality: "England", tier: 3 },
      { name: "Pervis Estupiñán", position: "LB", age: 27, nationality: "Ecuador", tier: 4 },
      { name: "Carlos Baleba", position: "CM", age: 21, nationality: "Cameroon", tier: 4 },
      { name: "Matt O'Riley", position: "CM", age: 25, nationality: "Denmark", tier: 4 },
      { name: "Yankuba Minteh", position: "RW", age: 21, nationality: "Gambia", tier: 4 },
      { name: "Kaoru Mitoma", position: "LW", age: 28, nationality: "Japan", tier: 4 },
      { name: "Danny Welbeck", position: "ST", age: 35, nationality: "England", tier: 3 },
      { name: "Georginio Rutter", position: "ST", age: 23, nationality: "France", tier: 3 },
    ],
  },
  {
    name: "Burnley",
    shortName: "Burnley",
    primaryColor: "#6C1D45",
    secondaryColor: "#99D6EA",
    players: [
      { name: "James Trafford", position: "GK", age: 23, nationality: "England", tier: 3 },
      { name: "Maxime Estève", position: "CB", age: 23, nationality: "France", tier: 3 },
      { name: "Axel Tuanzebe", position: "CB", age: 27, nationality: "England", tier: 2 },
      { name: "Connor Roberts", position: "RB", age: 30, nationality: "Wales", tier: 2 },
      { name: "Hjalmar Ekdal", position: "CB", age: 27, nationality: "Sweden", tier: 2 },
      { name: "Josh Cullen", position: "CM", age: 29, nationality: "Ireland", tier: 3 },
      { name: "Josh Brownhill", position: "CM", age: 30, nationality: "England", tier: 3 },
      { name: "Zian Flemming", position: "AM", age: 27, nationality: "Netherlands", tier: 3 },
      { name: "Jaidon Anthony", position: "LW", age: 26, nationality: "England", tier: 3 },
      { name: "Lyle Foster", position: "ST", age: 25, nationality: "South Africa", tier: 3 },
    ],
  },
  {
    name: "Chelsea",
    shortName: "Chelsea",
    primaryColor: "#034694",
    secondaryColor: "#FFFFFF",
    players: [
      { name: "Robert Sánchez", position: "GK", age: 28, nationality: "Spain", tier: 3 },
      { name: "Levi Colwill", position: "CB", age: 22, nationality: "England", tier: 4 },
      { name: "Wesley Fofana", position: "CB", age: 25, nationality: "France", tier: 3 },
      { name: "Reece James", position: "RB", age: 26, nationality: "England", tier: 4 },
      { name: "Marc Cucurella", position: "LB", age: 27, nationality: "Spain", tier: 4 },
      { name: "Moisés Caicedo", position: "DM", age: 24, nationality: "Ecuador", tier: 5 },
      { name: "Enzo Fernández", position: "CM", age: 25, nationality: "Argentina", tier: 5 },
      { name: "Cole Palmer", position: "AM", age: 23, nationality: "England", tier: 5 },
      { name: "Pedro Neto", position: "RW", age: 26, nationality: "Portugal", tier: 4 },
      { name: "Noni Madueke", position: "RW", age: 23, nationality: "England", tier: 4 },
      { name: "João Pedro", position: "ST", age: 24, nationality: "Brazil", tier: 4 },
      { name: "Nicolas Jackson", position: "ST", age: 24, nationality: "Senegal", tier: 4 },
    ],
  },
  {
    name: "Crystal Palace",
    shortName: "Crystal Palace",
    primaryColor: "#1B458F",
    secondaryColor: "#C4122E",
    players: [
      { name: "Dean Henderson", position: "GK", age: 28, nationality: "England", tier: 4 },
      { name: "Marc Guéhi", position: "CB", age: 25, nationality: "England", tier: 4 },
      { name: "Maxence Lacroix", position: "CB", age: 25, nationality: "France", tier: 3 },
      { name: "Daniel Muñoz", position: "RB", age: 29, nationality: "Colombia", tier: 3 },
      { name: "Tyrick Mitchell", position: "LB", age: 26, nationality: "England", tier: 3 },
      { name: "Adam Wharton", position: "CM", age: 21, nationality: "England", tier: 4 },
      { name: "Will Hughes", position: "CM", age: 30, nationality: "England", tier: 3 },
      { name: "Eberechi Eze", position: "AM", age: 27, nationality: "England", tier: 4 },
      { name: "Ismaïla Sarr", position: "RW", age: 27, nationality: "Senegal", tier: 4 },
      { name: "Jean-Philippe Mateta", position: "ST", age: 28, nationality: "France", tier: 4 },
    ],
  },
  {
    name: "Everton",
    shortName: "Everton",
    primaryColor: "#003399",
    secondaryColor: "#FFFFFF",
    players: [
      { name: "Jordan Pickford", position: "GK", age: 31, nationality: "England", tier: 4 },
      { name: "James Tarkowski", position: "CB", age: 33, nationality: "England", tier: 3 },
      { name: "Jarrad Branthwaite", position: "CB", age: 23, nationality: "England", tier: 4 },
      { name: "Nathan Patterson", position: "RB", age: 23, nationality: "Scotland", tier: 3 },
      { name: "Vitaliy Mykolenko", position: "LB", age: 26, nationality: "Ukraine", tier: 3 },
      { name: "Idrissa Gueye", position: "DM", age: 36, nationality: "Senegal", tier: 2 },
      { name: "James Garner", position: "CM", age: 24, nationality: "England", tier: 3 },
      { name: "Iliman Ndiaye", position: "AM", age: 25, nationality: "Senegal", tier: 4 },
      { name: "Jack Grealish", position: "LW", age: 30, nationality: "England", tier: 4 },
      { name: "Dwight McNeil", position: "LW", age: 26, nationality: "England", tier: 3 },
      { name: "Beto", position: "ST", age: 27, nationality: "Guinea-Bissau", tier: 3 },
    ],
  },
  {
    name: "Fulham",
    shortName: "Fulham",
    primaryColor: "#FFFFFF",
    secondaryColor: "#000000",
    players: [
      { name: "Bernd Leno", position: "GK", age: 33, nationality: "Germany", tier: 4 },
      { name: "Calvin Bassey", position: "CB", age: 25, nationality: "Nigeria", tier: 3 },
      { name: "Joachim Andersen", position: "CB", age: 29, nationality: "Denmark", tier: 4 },
      { name: "Kenny Tete", position: "RB", age: 30, nationality: "Netherlands", tier: 3 },
      { name: "Antonee Robinson", position: "LB", age: 28, nationality: "USA", tier: 4 },
      { name: "João Palhinha", position: "DM", age: 30, nationality: "Portugal", tier: 4 },
      { name: "Sander Berge", position: "CM", age: 27, nationality: "Norway", tier: 3 },
      { name: "Emile Smith Rowe", position: "AM", age: 25, nationality: "England", tier: 3 },
      { name: "Alex Iwobi", position: "RW", age: 29, nationality: "Nigeria", tier: 4 },
      { name: "Rodrigo Muniz", position: "ST", age: 24, nationality: "Brazil", tier: 3 },
      { name: "Raúl Jiménez", position: "ST", age: 34, nationality: "Mexico", tier: 3 },
    ],
  },
  {
    name: "Leeds United",
    shortName: "Leeds United",
    primaryColor: "#FFCD00",
    secondaryColor: "#1D428A",
    players: [
      { name: "Lucas Perri", position: "GK", age: 27, nationality: "Brazil", tier: 3 },
      { name: "Pascal Struijk", position: "CB", age: 26, nationality: "Netherlands", tier: 3 },
      { name: "Joe Rodon", position: "CB", age: 28, nationality: "Wales", tier: 3 },
      { name: "Jayden Bogle", position: "RB", age: 25, nationality: "England", tier: 3 },
      { name: "Ethan Ampadu", position: "DM", age: 25, nationality: "Wales", tier: 3 },
      { name: "Ilia Gruev", position: "CM", age: 24, nationality: "Bulgaria", tier: 3 },
      { name: "Brenden Aaronson", position: "AM", age: 25, nationality: "USA", tier: 3 },
      { name: "Daniel James", position: "RW", age: 28, nationality: "Wales", tier: 3 },
      { name: "Wilfried Gnonto", position: "LW", age: 22, nationality: "Italy", tier: 3 },
      { name: "Joel Piroe", position: "ST", age: 26, nationality: "Netherlands", tier: 3 },
    ],
  },
  {
    name: "Liverpool",
    shortName: "Liverpool",
    primaryColor: "#C8102E",
    secondaryColor: "#F6EB61",
    players: [
      { name: "Alisson Becker", position: "GK", age: 33, nationality: "Brazil", tier: 5 },
      { name: "Virgil van Dijk", position: "CB", age: 34, nationality: "Netherlands", tier: 5 },
      { name: "Ibrahima Konaté", position: "CB", age: 26, nationality: "France", tier: 4 },
      { name: "Conor Bradley", position: "RB", age: 22, nationality: "Northern Ireland", tier: 3 },
      { name: "Milos Kerkez", position: "LB", age: 21, nationality: "Hungary", tier: 4 },
      { name: "Alexis Mac Allister", position: "CM", age: 27, nationality: "Argentina", tier: 5 },
      { name: "Ryan Gravenberch", position: "CM", age: 23, nationality: "Netherlands", tier: 4 },
      { name: "Dominik Szoboszlai", position: "AM", age: 25, nationality: "Hungary", tier: 4 },
      { name: "Florian Wirtz", position: "AM", age: 22, nationality: "Germany", tier: 5 },
      { name: "Mohamed Salah", position: "RW", age: 33, nationality: "Egypt", tier: 5 },
      { name: "Cody Gakpo", position: "LW", age: 26, nationality: "Netherlands", tier: 4 },
      { name: "Hugo Ekitike", position: "ST", age: 23, nationality: "France", tier: 4 },
    ],
  },
  {
    name: "Manchester City",
    shortName: "Man City",
    primaryColor: "#6CABDD",
    secondaryColor: "#1C2C5B",
    players: [
      { name: "Ederson", position: "GK", age: 32, nationality: "Brazil", tier: 5 },
      { name: "Rúben Dias", position: "CB", age: 28, nationality: "Portugal", tier: 5 },
      { name: "Josko Gvardiol", position: "CB", age: 23, nationality: "Croatia", tier: 5 },
      { name: "Nathan Aké", position: "CB", age: 30, nationality: "Netherlands", tier: 4 },
      { name: "Rico Lewis", position: "RB", age: 21, nationality: "England", tier: 4 },
      { name: "Rodri", position: "DM", age: 29, nationality: "Spain", tier: 5 },
      { name: "Mateo Kovačić", position: "CM", age: 31, nationality: "Croatia", tier: 3 },
      { name: "Bernardo Silva", position: "CM", age: 31, nationality: "Portugal", tier: 5 },
      { name: "Phil Foden", position: "AM", age: 25, nationality: "England", tier: 5 },
      { name: "Savinho", position: "RW", age: 21, nationality: "Brazil", tier: 4 },
      { name: "Jérémy Doku", position: "LW", age: 23, nationality: "Belgium", tier: 4 },
      { name: "Erling Haaland", position: "ST", age: 25, nationality: "Norway", tier: 5 },
    ],
  },
  {
    name: "Manchester United",
    shortName: "Man United",
    primaryColor: "#DA291C",
    secondaryColor: "#FBE122",
    players: [
      { name: "André Onana", position: "GK", age: 30, nationality: "Cameroon", tier: 3 },
      { name: "Lisandro Martínez", position: "CB", age: 28, nationality: "Argentina", tier: 4 },
      { name: "Matthijs de Ligt", position: "CB", age: 26, nationality: "Netherlands", tier: 4 },
      { name: "Noussair Mazraoui", position: "RB", age: 28, nationality: "Morocco", tier: 3 },
      { name: "Luke Shaw", position: "LB", age: 30, nationality: "England", tier: 3 },
      { name: "Diogo Dalot", position: "RB", age: 27, nationality: "Portugal", tier: 3 },
      { name: "Manuel Ugarte", position: "DM", age: 24, nationality: "Uruguay", tier: 3 },
      { name: "Kobbie Mainoo", position: "CM", age: 20, nationality: "England", tier: 4 },
      { name: "Bruno Fernandes", position: "AM", age: 31, nationality: "Portugal", tier: 5 },
      { name: "Bryan Mbeumo", position: "RW", age: 26, nationality: "Cameroon", tier: 4 },
      { name: "Matheus Cunha", position: "ST", age: 26, nationality: "Brazil", tier: 4 },
      { name: "Benjamin Šeško", position: "ST", age: 22, nationality: "Slovenia", tier: 4 },
    ],
  },
  {
    name: "Newcastle United",
    shortName: "Newcastle",
    primaryColor: "#241F20",
    secondaryColor: "#FFFFFF",
    players: [
      { name: "Nick Pope", position: "GK", age: 33, nationality: "England", tier: 4 },
      { name: "Sven Botman", position: "CB", age: 26, nationality: "Netherlands", tier: 4 },
      { name: "Fabian Schär", position: "CB", age: 33, nationality: "Switzerland", tier: 3 },
      { name: "Dan Burn", position: "CB", age: 33, nationality: "England", tier: 3 },
      { name: "Kieran Trippier", position: "RB", age: 35, nationality: "England", tier: 3 },
      { name: "Bruno Guimarães", position: "CM", age: 27, nationality: "Brazil", tier: 5 },
      { name: "Sandro Tonali", position: "CM", age: 25, nationality: "Italy", tier: 4 },
      { name: "Anthony Gordon", position: "LW", age: 24, nationality: "England", tier: 4 },
      { name: "Jacob Murphy", position: "RW", age: 30, nationality: "England", tier: 3 },
      { name: "Nick Woltemade", position: "ST", age: 23, nationality: "Germany", tier: 4 },
    ],
  },
  {
    name: "Nottingham Forest",
    shortName: "Nott'm Forest",
    primaryColor: "#DD0000",
    secondaryColor: "#FFFFFF",
    players: [
      { name: "Matz Sels", position: "GK", age: 33, nationality: "Belgium", tier: 4 },
      { name: "Murillo", position: "CB", age: 23, nationality: "Brazil", tier: 4 },
      { name: "Nikola Milenković", position: "CB", age: 28, nationality: "Serbia", tier: 4 },
      { name: "Neco Williams", position: "RB", age: 24, nationality: "Wales", tier: 3 },
      { name: "Ola Aina", position: "LB", age: 28, nationality: "Nigeria", tier: 3 },
      { name: "Douglas Luiz", position: "CM", age: 27, nationality: "Brazil", tier: 3 },
      { name: "Elliot Anderson", position: "CM", age: 22, nationality: "England", tier: 3 },
      { name: "Morgan Gibbs-White", position: "AM", age: 25, nationality: "England", tier: 4 },
      { name: "Anthony Elanga", position: "LW", age: 23, nationality: "Sweden", tier: 4 },
      { name: "Callum Hudson-Odoi", position: "RW", age: 24, nationality: "England", tier: 3 },
      { name: "Chris Wood", position: "ST", age: 33, nationality: "New Zealand", tier: 4 },
    ],
  },
  {
    name: "Sunderland",
    shortName: "Sunderland",
    primaryColor: "#EB172B",
    secondaryColor: "#FFFFFF",
    players: [
      { name: "Robin Roefs", position: "GK", age: 22, nationality: "Netherlands", tier: 3 },
      { name: "Dan Ballard", position: "CB", age: 25, nationality: "Northern Ireland", tier: 3 },
      { name: "Aji Alese", position: "CB", age: 24, nationality: "England", tier: 2 },
      { name: "Trai Hume", position: "RB", age: 23, nationality: "Northern Ireland", tier: 3 },
      { name: "Dennis Cirkin", position: "LB", age: 23, nationality: "England", tier: 3 },
      { name: "Dan Neil", position: "CM", age: 23, nationality: "England", tier: 3 },
      { name: "Chris Rigg", position: "AM", age: 18, nationality: "England", tier: 3 },
      { name: "Romaine Mundle", position: "RW", age: 21, nationality: "England", tier: 2 },
      { name: "Wilson Isidor", position: "ST", age: 25, nationality: "France", tier: 3 },
      { name: "Eliezer Mayenda", position: "ST", age: 20, nationality: "Spain", tier: 3 },
    ],
  },
  {
    name: "Tottenham Hotspur",
    shortName: "Tottenham",
    primaryColor: "#132257",
    secondaryColor: "#FFFFFF",
    players: [
      { name: "Guglielmo Vicario", position: "GK", age: 29, nationality: "Italy", tier: 4 },
      { name: "Cristian Romero", position: "CB", age: 27, nationality: "Argentina", tier: 4 },
      { name: "Micky van de Ven", position: "CB", age: 24, nationality: "Netherlands", tier: 4 },
      { name: "Pedro Porro", position: "RB", age: 26, nationality: "Spain", tier: 4 },
      { name: "Destiny Udogie", position: "LB", age: 23, nationality: "Italy", tier: 4 },
      { name: "Rodrigo Bentancur", position: "CM", age: 28, nationality: "Uruguay", tier: 4 },
      { name: "Yves Bissouma", position: "DM", age: 29, nationality: "Mali", tier: 3 },
      { name: "James Maddison", position: "AM", age: 29, nationality: "England", tier: 4 },
      { name: "Dejan Kulusevski", position: "RW", age: 25, nationality: "Sweden", tier: 4 },
      { name: "Mohammed Kudus", position: "AM", age: 25, nationality: "Ghana", tier: 4 },
      { name: "Dominic Solanke", position: "ST", age: 28, nationality: "England", tier: 4 },
      { name: "Brennan Johnson", position: "RW", age: 24, nationality: "Wales", tier: 3 },
    ],
  },
  {
    name: "West Ham United",
    shortName: "West Ham",
    primaryColor: "#7A263A",
    secondaryColor: "#1BB1E7",
    players: [
      { name: "Alphonse Areola", position: "GK", age: 32, nationality: "France", tier: 3 },
      { name: "Konstantinos Mavropanos", position: "CB", age: 27, nationality: "Greece", tier: 3 },
      { name: "Max Kilman", position: "CB", age: 28, nationality: "England", tier: 3 },
      { name: "Vladimír Coufal", position: "RB", age: 33, nationality: "Czech Republic", tier: 2 },
      { name: "Emerson", position: "LB", age: 31, nationality: "Italy", tier: 3 },
      { name: "Guido Rodríguez", position: "DM", age: 31, nationality: "Argentina", tier: 3 },
      { name: "Tomáš Souček", position: "CM", age: 30, nationality: "Czech Republic", tier: 3 },
      { name: "Lucas Paquetá", position: "AM", age: 28, nationality: "Brazil", tier: 4 },
      { name: "Jarrod Bowen", position: "RW", age: 29, nationality: "England", tier: 4 },
      { name: "Niclas Füllkrug", position: "ST", age: 32, nationality: "Germany", tier: 3 },
    ],
  },
  {
    name: "Wolverhampton Wanderers",
    shortName: "Wolves",
    primaryColor: "#FDB913",
    secondaryColor: "#231F20",
    players: [
      { name: "José Sá", position: "GK", age: 32, nationality: "Portugal", tier: 3 },
      { name: "Craig Dawson", position: "CB", age: 35, nationality: "England", tier: 2 },
      { name: "Santiago Bueno", position: "CB", age: 26, nationality: "Mexico", tier: 3 },
      { name: "Ki-Jana Hoever", position: "RB", age: 26, nationality: "Netherlands", tier: 2 },
      { name: "Rayan Aït-Nouri", position: "LB", age: 24, nationality: "Algeria", tier: 4 },
      { name: "João Gomes", position: "CM", age: 24, nationality: "Brazil", tier: 4 },
      { name: "André", position: "CM", age: 23, nationality: "Brazil", tier: 3 },
      { name: "Jean-Ricner Bellegarde", position: "CM", age: 26, nationality: "France", tier: 3 },
      { name: "Hwang Hee-chan", position: "RW", age: 29, nationality: "South Korea", tier: 3 },
      { name: "Jørgen Strand Larsen", position: "ST", age: 25, nationality: "Norway", tier: 4 },
    ],
  },
];
